# Icons appear on the home page in this order
icons:
 - {icon: 'linkedin', font: 'font-awesome', link: 'https://www.linkedin.com/in/johannes-weytjens/'}
 - {icon: 'github', font: 'font-awesome', link: 'https://github.com/jpweytjens'}
 - {icon: 'google-scholar', font: 'academicons', link: 'https://scholar.google.com/citations?hl=en&user=R9eBhyoAAAAJ'}
 - {icon: 'orcid', font: 'academicons', link: 'https://orcid.org/0000-0002-2748-1524'}
 - {icon: 'bluesky', font: 'font-awesome', link: 'https://bsky.app/profile/peregrinus.be'}
 - {icon: 'strava', font: 'font-awesome', link: 'https://www.strava.com/athletes/17322406'}
