social:
 - {icon: 'linkedin', link: 'https://www.linkedin.com/in/johannes-weytjens-47b265105/'}
 - {icon: 'bluesky', link: 'https://bsky.app/profile/peregrinus.be'}
 - {icon: 'github', link: 'https://github.com/jpweytjens'}
 - {icon: 'strava', link: 'https://www.strava.com/athletes/17322406'}
 
academic:
 - {icon: 'orcid', link: 'https://orcid.org/0000-0002-2748-1524'}
 - {icon: 'osf', link: 'https://osf.io/v6wks/'}
 - {icon: 'ideas-repec', link: 'https://authors.repec.org/pro/pwe473/'}
 - {icon: 'google-scholar', link: 'https://scholar.google.com/citations?hl=en&user=R9eBhyoAAAAJ'}
